#!/usr/bin/env php
<?php
nameSpace App\Commands;

use Knp\Provider\ConsoleServiceProvider;
use \RecursiveDirectoryIterator;
use \RecursiveIteratorIterator;
use \RegexIterator;
use \RecursiveRegexIterator;


class CommandLauncher {
	public static function run($app,$sPath,$sNamespace){
		set_time_limit(0);

		$Directory = new RecursiveDirectoryIterator($sPath);
		$Iterator = new RecursiveIteratorIterator($Directory);
		$Regex = new RegexIterator($Iterator, '/^.+\.php$/i', RecursiveRegexIterator::GET_MATCH);

		foreach($Regex as $sClassName => $object){
			$sClassName = $sNamespace . implode('\\',explode('/',preg_replace('!\.php$!','',str_replace($sPath.'/','',$sClassName))));
			$app["console"]->add(new $sClassName());
		}

		$app["console"]->run();
	}
}

$app = require_once(__DIR__ ."/bootstrap.php");
$app->register(new ConsoleServiceProvider(),array(
	'console.name'				=> $gblCfg['application.name'],
	'console.version'			=> $gblCfg['application.version'],
	'console.project_directory'	=> __DIR__
));
CommandLauncher::run($app , __DIR__.'/App/Commands' , '\\App\\Commands\\');
